"""Structural post-closure development interfaces."""

from .candidate_triage import (
    ConnectivityCandidateMetadata,
    MetadataStatus,
    TriageDecision,
    TriageStatus,
    triage_candidate,
)

from .empirical_admission import (
    AdmissionDecision,
    AdmissionStatus,
    ConnectivityEmpiricalProtocol,
    evaluate_empirical_admission,
    protocol_from_mapping,
)

from .connectivity_adequacy import (
    AdequacyStage,
    ConnectivityCoordinate,
    ConnectivityEvidenceLevel,
    FavorableDirection,
    IncrementalEvidence,
    IncrementalVerdict,
    LadderStepEvidence,
    OperatorConnectivityState,
    PortabilitySummary,
    PortabilityVerdict,
    ScalarInsufficiencyWitness,
    SeparationOrigin,
    StateAdequacyVerdict,
    StateLadderSummary,
    audit_portability,
    audit_state_ladder,
    classify_incremental,
    classify_ladder_step,
    declared_operator_transition,
    scalar_insufficiency_witness,
)

__all__ = [
    "ConnectivityCandidateMetadata",
    "MetadataStatus",
    "TriageDecision",
    "TriageStatus",
    "AdmissionDecision",
    "AdmissionStatus",
    "ConnectivityEmpiricalProtocol",
    "protocol_from_mapping",
    "AdequacyStage",
    "ConnectivityCoordinate",
    "ConnectivityEvidenceLevel",
    "FavorableDirection",
    "IncrementalEvidence",
    "IncrementalVerdict",
    "LadderStepEvidence",
    "OperatorConnectivityState",
    "PortabilitySummary",
    "PortabilityVerdict",
    "ScalarInsufficiencyWitness",
    "SeparationOrigin",
    "StateAdequacyVerdict",
    "StateLadderSummary",
    "audit_portability",
    "audit_state_ladder",
    "classify_incremental",
    "classify_ladder_step",
    "declared_operator_transition",
    "scalar_insufficiency_witness",
    "evaluate_empirical_admission",
    "triage_candidate",
]
